name: "Antel Consumo"
version: "1.1.7"
slug: "antel_consumo"
description: "Scraper de consumo de internet Antel (Uruguay)"
url: "https://github.com/matiasca89/hacs-antel"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
options:
  username: ""
  password: ""
  scan_interval: 60
  service_id: ""
schema:
  username: str
  password: str
  scan_interval: int
  service_id: str?
homeassistant_api: true
