name: "Antel Consumo"
version: "1.3.13"
slug: "antel_consumo"
description: "Scraper de consumo de internet Antel (Uruguay)"
url: "https://github.com/matiasca89/hacs-antel"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
options:
  username: ""
  password: ""
  scan_interval: 60
  service_id: ""
  renewal_day: 1
  timezone: "America/Montevideo"
schema:
  username: str
  password: str
  scan_interval: int
  service_id: str?
  renewal_day: int?
  timezone: str?
homeassistant_api: true
